# Generated by Django 4.1.5 on 2023-01-27 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('descriptions', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('particular_name', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('rate', models.FloatField()),
                ('value', models.FloatField()),
                ('product_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product_category')),
            ],
        ),
    ]
