# Generated by Django 4.1.5 on 2023-02-02 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_product_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product_category',
            new_name='ProductCategory',
        ),
    ]
