# Generated by Django 4.1.4 on 2023-01-22 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(choices=[('january', 'january'), ('July', 'July'), ('February', 'February'), ('August', 'August'), ('March', 'March'), ('September', 'September'), ('April', 'April'), ('October', 'October'), ('May', 'May'), ('November', 'November'), ('June', 'June'), ('December', 'December')], max_length=50)),
                ('transfer_capital', models.FloatField()),
                ('laundary_total', models.FloatField()),
                ('CashIn_total', models.FloatField()),
                ('Cashout_total', models.FloatField()),
                ('Bank_total', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='TransactionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='BillData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_No', models.CharField(max_length=50, null=True)),
                ('date', models.DateField()),
                ('particulars', models.CharField(max_length=100)),
                ('transaction_amount', models.FloatField()),
                ('transaction_type', models.CharField(choices=[('cash_In', 'cash_In'), ('cash_out', 'cash_out'), ('fonepay', 'fonepay'), ('cheque', 'cheque')], default='cash_In', max_length=50)),
                ('transaction_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bill_management.transactioncategory')),
            ],
        ),
    ]
