# Generated by Django 4.1.4 on 2023-01-22 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlysummary',
            name='month',
            field=models.CharField(choices=[('january', 'january'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], max_length=50),
        ),
    ]
